export const ERROR_CODES = {
  // General
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // Authentication
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",

  // Verification Code
  VERIFICATION_CODE_NOT_FOUND: "VERIFICATION_CODE_NOT_FOUND",
  VERIFICATION_CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",
  INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
  INVALID_VERIFICATION_PURPOSE: "INVALID_VERIFICATION_PURPOSE",

  // Password
  CURRENT_PASSWORD_INCORRECT: "CURRENT_PASSWORD_INCORRECT",
  PASSWORD_SAME_AS_CURRENT: "PASSWORD_SAME_AS_CURRENT",
  PASSWORD_RESET_CODE_INVALID: "PASSWORD_RESET_CODE_INVALID",
  PASSWORD_RESET_CODE_EXPIRED: "PASSWORD_RESET_CODE_EXPIRED",

  // User
  USER_PROFILE_NOT_FOUND: "USER_PROFILE_NOT_FOUND",
  USER_ALREADY_DELETED: "USER_ALREADY_DELETED",
  USER_NOT_DELETED: "USER_NOT_DELETED",

  // Recipe
  RECIPE_NOT_FOUND: "RECIPE_NOT_FOUND",
  RECIPE_ALREADY_DELETED: "RECIPE_ALREADY_DELETED",
  RECIPE_NOT_DELETED: "RECIPE_NOT_DELETED",
  RECIPE_EDIT_FORBIDDEN: "RECIPE_EDIT_FORBIDDEN",
  RECIPE_DELETE_FORBIDDEN: "RECIPE_DELETE_FORBIDDEN",
  INVALID_RECIPE_CATEGORY: "INVALID_RECIPE_CATEGORY",

  // Category
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
  CATEGORY_IN_USE: "CATEGORY_IN_USE",
  CATEGORY_INACTIVE: "CATEGORY_INACTIVE",

  // Rating
  RATING_NOT_FOUND: "RATING_NOT_FOUND",
  RATING_ALREADY_EXISTS: "RATING_ALREADY_EXISTS",
  CANNOT_RATE_OWN_RECIPE: "CANNOT_RATE_OWN_RECIPE",

  // Bookmark
  BOOKMARK_NOT_FOUND: "BOOKMARK_NOT_FOUND",
  BOOKMARK_ALREADY_EXISTS: "BOOKMARK_ALREADY_EXISTS",

  // Comment
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  COMMENT_DELETE_FORBIDDEN: "COMMENT_DELETE_FORBIDDEN",
  COMMENT_REPLY_FORBIDDEN: "COMMENT_REPLY_FORBIDDEN",

  // Reaction
  REACTION_NOT_FOUND: "REACTION_NOT_FOUND",
  REACTION_ALREADY_EXISTS: "REACTION_ALREADY_EXISTS",

  // Follow
  FOLLOW_NOT_FOUND: "FOLLOW_NOT_FOUND",
  ALREADY_FOLLOWING: "ALREADY_FOLLOWING",
  NOT_FOLLOWING: "NOT_FOLLOWING",
  CANNOT_FOLLOW_SELF: "CANNOT_FOLLOW_SELF",

  // Notification
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_ACCESS_FORBIDDEN: "NOTIFICATION_ACCESS_FORBIDDEN",

  // Support Ticket
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_ACCESS_FORBIDDEN: "TICKET_ACCESS_FORBIDDEN",
  TICKET_ALREADY_CLOSED: "TICKET_ALREADY_CLOSED",
  TICKET_NOT_CLOSED: "TICKET_NOT_CLOSED",
  TICKET_REPLY_FORBIDDEN: "TICKET_REPLY_FORBIDDEN",
};
